[package]
name = "simplecv"
version = "0.0.1"
authors = ["Mengxiao Lin <linmx0130@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
description = "A simple computer vision library."

[dependencies]
image = "0.21.0"
ndarray = "0.12.1"
num = "*"
