[package]
name = "simplecv"
version = "0.1.0"
authors = ["Mengxiao Lin <linmx0130@gmail.com>"]
edition = "2018"

[dependencies]
image = {git="https://github.com/PistonDevelopers/image.git"} 
ndarray = "0.12.1"
